### ISSUE TITLE
new field issue

### ISSUE THREAD

**Issue by kiranjeetgill** [ansarhusain7/Custom-mail-with-attachment-magento2#1]
I am using this module and I add some fields. can you guide me in custom_form.html file how can i add new fields:
We can't process your request right now. Sorry, that's all we know.Notice: Undefined index: firstname in app/code/CustomForm/MailAttachment/Controller/Index/Submit.php on line 106

<=======submit_form.html==========>
<table>
   <tr>
     <td>
	   <table>
	   <tr><td>Date:</td><td>{{trans "%date" date=$data.datetwo}}</td></tr>
	   
	   <tr><td>Customer Name:</td><td>{{trans "%cname" cname=$data.customername}}</td></tr>
	 
			<tr><td>First Name:</td><td>{{trans "%fname" fname=$data.firstname}}</td></tr>
			<tr><td>Last Name: </td><td>{{trans "%lname" lname=$data.lastname}}</td></tr>
			<tr><td>Email:</td><td>{{trans "%email" email=$data.email}}</td></tr>
			<tr><td>Telephone:</td><td>{{trans "%telephone" telephone=$data.telephone}}</td></tr>
	   </table>
   </td>
   </tr>
</table>

**Comment by kiranjeetgill** [comment]
Content-->block
I create one block and use this code
<p>{{block class="Magento\Framework\View\Element\Template" template="CustomForm_MailAttachment::customform.phtml" }}</p>
![capture](https://user-images.githubusercontent.com/43862471/46500039-ca4daf00-c7ef-11e8-9338-d497ebbe5103.PNG)

text field is not clickable. Can you guide me where I did mistake?

**Comment by ansarhusain7** [comment]
@kiranjeetgill 

you can add fields in phtml page 
CustomForm/MailAttachment/view/frontend/templates/customform.phtml

And just call these fields in email template 
CustomForm/MailAttachment/view/frontend/email/custom_form.html

Thanks
